image: python:3.9-buster

before_script:
  - python -m pip install pip setuptools wheel --upgrade --force-reinstall --quiet --no-cache-dir
  - pip install poetry --quiet --no-cache-dir
  - poetry config virtualenvs.in-project true
  - make install-development

stages:
  - testing
  - coverage
  - building
  - publishing

.testing_template: &python_matrix
  stage: testing
  script: make test

testing:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

testing:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

testing:py3.8:
  <<: *python_matrix
  image: python:3.8-buster

testing:py3.9:
  <<: *python_matrix

code quality:
  stage: coverage
  needs:
    - testing:py3.6
    - testing:py3.7
    - testing:py3.8
    - testing:py3.9
  script: make coverage

build package:
  stage: building
  script: make build
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}
    paths:
      - dist
    expire_in: 1 week
  only:
    - master
    - tags

deployment:
  stage: publishing
  dependencies:
    - build package
  script: make upload
  only:
    - master
